theme: jekyll-theme-midnight
title: Welcome to Christopher Hess's ePortfolio!
description: This repository will begin for my capstone project at Southern New Hampshire University. It will expand with additional projects over time.
